alert:
- debug
description: This rule detects a DHCP server in which a specified Callout DLL (in registry) was loaded
filter:
- query:
    query_string:
      query: (data.win.system.eventID:"1033" AND data.win.eventdata.source Name:"Microsoft\-Windows\-DHCP\-Server")
index: wazuh-alerts-3.x-*
name: sigma_win_susp_dhcp_config
priority: 1
realert:
  minutes: 0
type: any


