alert:
- debug
description: This rule detects a DHCP server error in which a specified Callout DLL (in registry) could not be loaded
filter:
- query:
    query_string:
      query: (data.win.system.eventID:("1031" OR "1032" OR "1034") AND data.win.eventdata.source Name:"Microsoft\-Windows\-DHCP\-Server")
index: wazuh-alerts-3.x-*
name: sigma_win_susp_dhcp_config_failed
priority: 1
realert:
  minutes: 0
type: any
