alert:
- debug
description: Detects changes to RDP terminal service sensitive settings
filter:
- query:
    query_string:
      query: data.win.eventdata.targetObject.keyword:(*\\services\\TermService\\Parameters\\ServiceDll* OR *\\Control\\Terminal\ Server\\fSingleSessionPerUser* OR *\\Control\\Terminal\ Server\\fDenyTSConnections*)
index: wazuh-alerts-3.x-*
name: sigma_sysmon_rdp_settings_hijack
priority: 2
realert:
  minutes: 0
type: any
