language: python
python:
  - 3.5
  - 3.6
services:
    - elasticsearch
cache: pip
before_install:
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.4.deb && sudo service elasticsearch restart
install:
  - pip install -r tools/requirements-devel.txt 
script:
  - make test
  - make test-backend-es-qs
