language: python
python:
  - 3.6
cache: pip
install:
  - pip install pyyaml
  - pip install yamllint

script:
  - yamllint .
  - for f in rules/windows/builtin/*; do python tools/sigmac.py -v $f; done
