logsources:
  windows-application:
    product: windows
    service: application
    index: logs-endpoint-winevent-application-*
  windows-security:
    product: windows
    service: security
    index: logs-endpoint-winevent-security-*
  windows-sysmon:
    product: windows
    service: sysmon
    index: logs-endpoint-winevent-sysmon-*
  windows-system:
    product: windows
    service: system
    index: logs-endpoint-winevent-system-*
  windows-wmi:
    product: windows
    service: wmi
    index: logs-endpoint-winevent-wmiactivity-*
  windows-powershell:
    product: windows
    service: powershell
    index: logs-endpoint-winevent-powershell-*
  windows-powershell-classic:
    product: windows
    service: powershell-classic
    index: logs-endpoint-winevent-powershell-*
defaultindex: logs-*
