alert:
- debug
description: Detects registry changes to Office macro settings
filter:
- query:
    query_string:
      query: (data.win.eventdata.targetObject.keyword:(*\\Security\\Trusted\ Documents\\TrustRecords OR *\\Security\\AccessVBOM OR *\\Security\\VBAWarnings) AND data.win.eventdata.eventType:("SetValue" OR "DeleteValue" OR "CreateValue"))
index: wazuh-alerts-3.x-*
name: a166f74e-bf44-409d-b9ba-ea4b2dd8b3cd_0
priority: 2
realert:
  minutes: 0
type: any


