alert:
- debug
description: This rule detects a DHCP server error in which a specified Callout DLL (in registry) could not be loaded
filter:
- query:
    query_string:
      query: (data.win.system.eventID:("1031" OR "1032" OR "1034") AND source_name:"Microsoft\-Windows\-DHCP\-Server")
index: wazuh-alerts-3.x-*
name: 75edd3fd-7146-48e5-9848-3013d7f0282c_0
priority: 1
realert:
  minutes: 0
type: any


