alert:
- debug
description: This rule detects a DNS server error in which a specified plugin DLL (in registry) could not be loaded
filter:
- query:
    query_string:
      query: data.win.system.eventID:("150" OR "770")
index: wazuh-alerts-3.x-*
name: cbe51394-cd93-4473-b555-edf0144952d9_0
priority: 1
realert:
  minutes: 0
type: any


