alert:
- debug
description: This rule detects a DHCP server in which a specified Callout DLL (in registry) was loaded
filter:
- query:
    query_string:
      query: (data.win.system.eventID:"1033" AND source_name:"Microsoft\-Windows\-DHCP\-Server")
index: wazuh-alerts-3.x-*
name: 13fc89a9-971e-4ca6-b9dc-aa53a445bf40_0
priority: 1
realert:
  minutes: 0
type: any


