title: Azure Kubernetes Secret or Config Object Access
id: 7ee0b4aa-d8d4-4088-b661-20efdf41a04c
description: Identifies when a Kubernetes account access a sensitve objects such as configmaps or secrets.
author: Austin Songer
status: experimental
date: 2021/08/07
references:
    - https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftkubernetes
logsource:
  service: azure.activitylogs
detection:
    selection1:
          properties.message: MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/CONFIGMAPS/WRITE 
    selection2:
          properties.message: MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/CONFIGMAPS/DELETE
    selection3:
          properties.message: MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SECRETS/WRITE
    selection4:
          properties.message: MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SECRETS/DELETE
    condition: selection1 or selection2 or selection3 or selection4
level: medium
tags:
    - attack.impact
falsepositives:
- Sensitive objects may be accessed by a system administrator. Verify whether the user identity, user agent, and/or hostname should be making changes in your environment. Sensitive objects accessed from unfamiliar users should be investigated. If known behavior is causing false positives, it can be exempted from the rule.

