title: Events Deleted
id: 3132570d-cab2-4561-9ea6-1743644b2290
related:
    - id: 225d8b09-e714-479c-a0e4-55e6f29adf35
status: experimental
author: Leo Tsaousis (@laripping)
date: 2024-01-25
description: |
    Detects when Events are deleted in Kubernetes. An adversary may delete Kubernetes events in an attempt to evade detection
logsource:
    product: kubernetes
    service: audit_logs
detection:
    selection:
        verb: delete
        resource: events
    condition: selection
level: medium
tags: attack.T1070
references: 
    - https://microsoft.github.io/Threat-Matrix-for-Kubernetes/techniques/Delete%20K8S%20events/
falsepositives:
    - Unknown
