title: Authentications To MBI And HBI Application Using Single Factor Authentication
id: cd0ff69f-f875-4058-a94d-405b0dbe8071
status: experimental
author: MikeDuddington, '@dudders1'
date: 2022/07/28
description: Detect when authentications to important application(s) only required single-factor authentication
references:
  - https://docs.microsoft.com/en-gb/azure/active-directory/fundamentals/security-operations-user-accounts
logsource:
  product: azure
  service: signinlogs
detection:
  selection:
    Status: 'Success'
    AppId: 'Insert Application ID use OR for multiple'
    AuthenticationRequirement: 'singleFactorAuthentication'
  condition: selection
level: medium
falsepositives:
  - If this was approved by System Administrator.
tags:
  - attack.t1078