title: Google Workspace Application Access Levels Modified
id: 22f2fb54-5312-435d-852f-7c74f81684ca
description: |
  Detects when an access level is changed for a google workspace application. An access level is part of BeyondCorp Enterprise which is Google Workspace's way of enforcing Zero Trust model.
  An adversay would be able to remove access levels to gain easier access to google workspace resources.
references:
    - https://developers.google.com/admin-sdk/reports/v1/appendix/activity/admin-application-settings
    - https://support.google.com/a/answer/9261439
author: Bryan Lim
date: 2023/09/12
status: experimental
tags:
  - attack.persistence
  - attack.t1098.003
logsource:
  product: gcp
  service: google_workspace.admin
detection:
  selection:
    eventService: admin.googleapis.com
    eventName: CHANGE_APPLICATION_SETTINGS
    setting_name|startswith: ContextAwareAccess
  condition: selection
fields:
  - timestamp
  - setting_name
  - eventName
  - ipAddress
  - actor.email
falsepositives:
- Legitimate administrative activities changing the access levels for an application
level: medium