title: System Network Configuration Discovery
id: 42df45e7-e6e9-43b5-8f26-bec5b39cc239
status: stable
description: Detects system network configuration discovery commands
author: Ömer Günal, oscd.community
date: 2020/10/08
references:
    - https://attack.mitre.org/techniques/T1016/
logsource:
    product: linux
    category: process_creation
detection:
    selection:
        CommandLine|contains:
          - 'ifconfig '
          - 'ip '
          - 'arp '
          - '/etc/resolv.conf'
          - 'systemd-resolve '
          - 'route '
          - 'netstat'
          - 'ss '
    condition: selection
falsepositives:
    - Legitimate administration activities
level: low
tags:
    - attack.discovery
    - attack.t1016
