title: Bitbucket Audit Log Configuration Update Detected
id: 6aa12161-235a-4dfb-9c74-fe08df8d8da1
status: experimental
description: Detects changes to bitbucket audit log configurations. The required log level is "Basic" for these audit events.
references:
    - https://confluence.atlassian.com/bitbucketserver/view-and-configure-the-audit-log-776640417.html
author: Muhammad Faisal (@faisalusuf)
date: 2024/02/25
tags:
    - attack.t1562.001
logsource:
    product: bitbucket
    service: audit
detection:
    selection:
        auditType.category: 'Auditing'
        auditType.action: 'Audit log configuration updated'
    condition: selection
falsepositives:
    - Legitimate user activity.
level: medium
