# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sigma Rule Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"
    # paths:
    #   - "deprecated/**.yml"
    #   - "rules-compliance/**.yml"
    #   - "rules-dfir/**.yml"
    #   - "rules-emerging-threats/**.yml"
    #   - "rules-placeholder/**.yml"
    #   - "rules-threat-hunting/**.yml"
    #   - "rules/**.yml"
    #   - "unsupported/**.yml"
  pull_request_target:
    branches:
      - master
    # paths:
    #   - "deprecated/**.yml"
    #   - "rules-compliance/**.yml"
    #   - "rules-dfir/**.yml"
    #   - "rules-emerging-threats/**.yml"
    #   - "rules-placeholder/**.yml"
    #   - "rules-threat-hunting/**.yml"
    #   - "rules/**.yml"
    #   - "unsupported/**.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  EVTX_BASELINE_VERSION: v0.7

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3

  test-sigma-logsource:
    runs-on: ubuntu-latest
    #needs: yamllint
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11
    - name: Test Sigma logsource
      run: |
        pip install PyYAML colorama
        python tests/test_logsource.py

  