name: Update LimaCharlie Sigma Rules
on:
  push:
    branches:
      - master
      - lc-automation

jobs:
  build:
    name: Generate Rules
    runs-on: ubuntu-latest
    steps:
      - name: Get Generation Script
        run: wget https://raw.githubusercontent.com/refractionPOINT/sigma/lc-automation/.github/workflows/generate_all.py
      - name: Generate
        run: python3 ./generate_all.py
      - name: List Rules
        run: ls -lah ./dr_rules/