name: Update LimaCharlie Sigma Rules
on:
  check_run:
    types: [completed]

jobs:
  build:
    name: Generate Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rule Branch
        uses: actions/checkout@master
        with:
          ref: lc-rules
          token: ${{ github.token }}
      - name: Set Git Ident
        run: git config --global user.email "ops@limacharlie.io"; git config --global user.name "LimaCharlie Ops"
      - name: Rebase Latest
        run: git rebase origin/master
      - name: Get Generation Script
        run: wget https://raw.githubusercontent.com/refractionPOINT/sigma/lc-automation/.github/workflows/generate_all.py
      - name: Generate
        run: ls -lah ./ ; python3 ./generate_all.py
      - name: Commit Rules
        run: git add --all ./lc-rules/ ; git commit -m "Update to rules." ; git push -f