title: Suspicious Windows Binaries Usage For Ingress Tool Transfer
id: 8762a1ab-7013-44cc-8e75-1e2823bb16fc
status: experimental
description: Detects usage of windows native binaries for ingress tool transfer from referened url.
author: Swachchhanda Shrawan Poudel
date: 2023/11/09
references:
    - https://lolbas-project.github.io/lolbas/Binaries/AppInstaller/
    - https://lolbas-project.github.io/lolbas/Binaries/Certoc/
    - https://lolbas-project.github.io/lolbas/Binaries/Certutil/
    - https://lolbas-project.github.io/lolbas/Binaries/Desktopimgdownldr/
    - https://lolbas-project.github.io/lolbas/Binaries/IMEWDBLD/
    - https://lolbas-project.github.io/lolbas/Binaries/Ieexec/
    - https://lolbas-project.github.io/lolbas/Binaries/Installutil/
    - https://lolbas-project.github.io/lolbas/Binaries/MpCmdRun/
    - https://lolbas-project.github.io/lolbas/Binaries/Msedge/
    - https://lolbas-project.github.io/lolbas/Binaries/Mshta/
    - https://lolbas-project.github.io/lolbas/Binaries/Presentationhost/
    - https://lolbas-project.github.io/lolbas/Binaries/Regsvr32/
    - https://lolbas-project.github.io/lolbas/Binaries/msedge_proxy/
    - https://lolbas-project.github.io/lolbas/OtherMSBinaries/MsoHtmEd/
    - https://lolbas-project.github.io/lolbas/OtherMSBinaries/Msxsl/
    - https://lolbas-project.github.io/lolbas/OtherMSBinaries/ProtocolHandler/
    - https://lolbas-project.github.io/lolbas/OtherMSBinaries/Squirrel/
    - https://lolbas-project.github.io/lolbas/OtherMSBinaries/Update/
tags:
    - attack.t1105
logsource:
    category: process_creation
    product: windows
detection:
    selection_image:
        - Image|endswith:
              - '\AppInstaller.exe'
              - '\CertOC.exe'
              - '\certutil.exe'
              - '\Desktopimgdownldr.exe'
              - '\IMEWDBLD.exe'
              - '\ieexec.exe'
              - '\InstallUtil.exe'
              - '\MpCmdRun.exe'
              - '\msedge.exe'
              - '\Mshta.exe'
              - '\Presentationhost.exe'
              - '\regsvr32.exe'
              - '\msedge_proxy.exe'
              - '\MsoHtmEd.exe'
              - '\Mspub.exe'
              - '\msxsl.exe'
              - '\ProtocolHandler.exe'
              - '\squirrel.exe'
              - '\update.exe'
        - CommandLine|contains:
              -'appinstaller'
              -'certoc'
              -'certutil'
              -'Desktopimgdownldr'
              -'IMEWDBLD'
              -'ieexec'
              -'InstallUtil'
              -'MpCmdRun'
              -'msedge'
              -'Mshta'
              -'Presentationhost'
              -'regsvr32'
              -'msedge_proxy'
              -'MsoHtmEd'
              -'Mspub'
              -'msxsl'
              -'ProtocolHandler.exe"
              -'squirrel'
              -'update.exe'
              -'download'
    selection_http:
        CommandLine|contains: 'http'
    condition: all of selection_*
falsepositives:
    - Unknown
level: medium
